// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Re-run: npm run images
export type SiteImage = {
  src: string;
  width: number;
  height: number;
  bytes: number;
  blur: string;
};

export const images = {
  "hero-alphabet": {
    "src": "/images/hero-alphabet.webp",
    "width": 1100,
    "height": 733,
    "bytes": 105244,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoYABAAPt1gqU2opaQiMAgBEBuJQBOmUAAvd30N7wAA/kibVJtLQZ3UCmPJS1UeCd2nBL7GTY2zMoxxc0J9a78wAAA="
  },
  "fly-rainbow": {
    "src": "/images/fly-rainbow.webp",
    "width": 480,
    "height": 480,
    "bytes": 15442,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACQBQCdASoYABgAPtlWpEyoJKOiN/VYAQAbCWgAnTKEfjDftZAZX38Ma2sx2E4n7PfFLG/wAAD8TN880SeylEtEtus/uOe/ilUspy83x5qIKnAhy3T/m1XZ0xxULlZkdf75n2aOSYTIOjRSOiNCkkPyKeFEnsuJMoAAAA=="
  },
  "prod-busyboard": {
    "src": "/images/prod-busyboard.webp",
    "width": 1000,
    "height": 1000,
    "bytes": 107914,
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwBQCdASoYABgAPt1ap04opKOiMBgIARAbiUATo/+QMDZQPhQ+R+JRL8ySIbEd6neAaPgAAP7yMrUWLQUxOxrhNLHSLtfygkYEqhotMcMOs62vD+bO9u98wTngnryfPPx4YCRh5uGYmAAA"
  },
  "prod-rainbow": {
    "src": "/images/prod-rainbow.webp",
    "width": 1000,
    "height": 1000,
    "bytes": 55592,
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwBQCdASoYABgAPt1UqEyopCQiMBgMARAbiWwAsQmKoGBsCyrTwWAL/prs9Yc2i9LO7crS/wAA/vTb7uAZcL7IIJbwtBW1CVld6gJdaWeRSmCt6mgzi6nXm74S3pl70kfZIaHM/cOwTXsNlTV0fV2Kkbk3Fp0DiFf6k4DnMQCmt6P4yFO9UOfA3dia5MYAAAA="
  },
  "prod-abc": {
    "src": "/images/prod-abc.webp",
    "width": 1000,
    "height": 1000,
    "bytes": 112438,
    "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoYABgAPt1orFCopaQqqAgBUBuJQBYj5lJ+gEHwFn0JtoMRX3+XLAAA/G58rXg1shlvwXvcjnbcg8AQoYKJAuPtSuP+FMDTlSGEE75fxS+Itsv6l9vDfH8ThCuMTAAA"
  },
  "prod-abacus": {
    "src": "/images/prod-abacus.webp",
    "width": 448,
    "height": 448,
    "bytes": 11818,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoYABgAPt1eqE6opKOiMBgIARAbiUAWoSjQK5T4JxXEdkyP6d/63axZywAA/vOCsez7eoE6LtlTU4C9vAU1GcyD0x+NKZMh2O1WUqwBSm+dv1vAFOTFAjv0SmpEwdFy/gd4AA=="
  },
  "prod-quietbook": {
    "src": "/images/prod-quietbook.webp",
    "width": 300,
    "height": 300,
    "bytes": 19982,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBQCdASoYABgAPt1cqU6opKQiMBgIARAbiWIAuwAQ34hWL74Ig21rTi/rgu+vDyIlYAAA/mUmjDpYi84BXXKbBSkNbI6Iuo37aFmUBInu3lWaUqip7D6b+4xzPa2HOwVQrVX6yndfKY1XIR9IxW0IXLAR4AAA"
  },
  "prod-lacing": {
    "src": "/images/prod-lacing.webp",
    "width": 800,
    "height": 800,
    "bytes": 49402,
    "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwBACdASoYABgAPt1epUyopSOiMBgMARAbiUAWnQHpXb8lFU32T+8S9SK5k10wFwAA/vTf13Umhyv7WYWmU+4Ra2d1Ebf+HbKx2iTSECoaLu310QN0X2tw/imIHOQ3VQvDAcF9p1eacNcdB5jJiFY2bwYYAA=="
  },
  "prod-gears": {
    "src": "/images/prod-gears.webp",
    "width": 750,
    "height": 590,
    "bytes": 10502,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwBACdASoYABMAPt1eqU2opSQiKA1REBuJZADN8oPEAF71oD56wkHRPdOW55cAAP76EQ+ehJRhNuKSOdR2aPJIqbgot7GcUa0PFsMLztVbGJDoBQkC62EmAAA="
  },
  "craft-hands": {
    "src": "/images/craft-hands.webp",
    "width": 443,
    "height": 612,
    "bytes": 30228,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwBACdASoRABgAPt1mq1EopSOiqAgBEBuJQBfs7rAcs481oeCg9V8s55cAW3sAAP7jpbErn2G739WifFGtwsvIMn3Dp/JZbPjvewWIU1xbs+I2siD26nCKDO9l65XcnQ3qgS1Gphlog6TgAAA="
  },
  "gallery-alphabet": {
    "src": "/images/gallery-alphabet.webp",
    "width": 900,
    "height": 789,
    "bytes": 92952,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQBACdASoYABUAPs1ao0ynpaMiN/qoAPAZiWUAAN3qpmmZHRfrPE+lRBfvroAA1lor2m9vYKRwHyx+xREnNjgkoRupxdqgYOclYu0f5G9nSeeBFFB2qgrmL/GAAAAA"
  },
  "gallery-felt": {
    "src": "/images/gallery-felt.webp",
    "width": 340,
    "height": 270,
    "bytes": 15916,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwBACdASoYABMAPt1YqEyopSQiMBgMARAbiWIAnTLeuWgVI8SfkxW8u1jcHtbeInAA/tNXMaJloNAr0qhbAkggaaelLtbVGc4TQbEGJ4UQa8ydsFR9kgyP1LujUWJ+2VS5ZZdkAAA="
  },
  "gallery-flatlay": {
    "src": "/images/gallery-flatlay.webp",
    "width": 800,
    "height": 800,
    "bytes": 70060,
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwBACdASoYABgAPt1cqUyopSQiKA1REBuJagCdMoAAyQGGO46PN+0C/Wq7f3LQAP6UwvzZjE4VluQ2YYF3L0Oy25wchx1dPAHv+pWg1v0uRO0a8nv+TkYl4rfMxRga5w0OpDJUtuN2FkeLFfhfS+xIv2y9Zo0xbFOTPKKxH5I/FeHm7XsftfXZoJe0jmKAAAA="
  },
  "gallery-busyboard": {
    "src": "/images/gallery-busyboard.webp",
    "width": 500,
    "height": 380,
    "bytes": 22738,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQBACdASoYABIAPt1apEyopSOiMAgBEBuJQBWGXkBp0sMgeqG1YJWQkZbBggAA/u3cBWnQdWxPmRE07TAU+Mx0sNEjWp006Nv4U8OPPKw8aOotVGjy1y1g/bULea9xOvsE2QhAhgJn0u0gAAA="
  }
} as const satisfies Record<string, SiteImage>;
