/**
 * Image preparation pipeline.
 * Crops source photographs, optimizes them to WebP at healthy display sizes,
 * generates tiny blur placeholders and emits typed metadata consumed by the app.
 *
 * Usage: node scripts/prepare-images.mjs
 */
import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
// Search results are stored one level above the project folder.
const src = (p) => join(root, "..", "image-search", p);
const out = join(root, "public", "images");
mkdirSync(out, { recursive: true });

/** name -> { file, width, quality, crop? } */
const JOBS = [
  // Hero
  { name: "hero-alphabet", file: "wooden-alphabet-puzzle-letters-toy-for-k-3.jpg", width: 1100, quality: 82 },
  { name: "fly-rainbow", file: "wooden-rainbow-stacker-montessori-toy-co-2.jpg", width: 480, quality: 80 },
  // Products
  { name: "prod-busyboard", file: "handmade-wooden-busy-board-montessori-to-4.jpg", width: 1000, quality: 82 },
  { name: "prod-rainbow", file: "wooden-rainbow-stacker-montessori-toy-co-1.jpg", width: 1000, quality: 82 },
  {
    // square centre-crop of the alphabet puzzle for the product card
    name: "prod-abc",
    file: "wooden-alphabet-puzzle-letters-toy-for-k-3.jpg",
    width: 1000,
    quality: 82,
    cropSquare: true,
  },
  { name: "prod-abacus", file: "wooden-abacus-counting-beads-toy-child-h-1.jpg", width: 1000, quality: 82 },
  { name: "prod-quietbook", file: "felt-quiet-book-busy-book-educational-fa-3.jpg", width: 1000, quality: 82 },
  { name: "prod-lacing", file: "wooden-shape-sorter-toy-colorful-white-b-1.jpg", width: 1000, quality: 82 },
  {
    // gear board: the source photo has a small baby inset in the bottom-right corner — crop it away
    name: "prod-gears",
    file: "handmade-wooden-busy-board-montessori-to-1.jpg",
    width: 1000,
    quality: 82,
    crop: { top: 0, left: 0, width: 750, height: 590 }, // 750x590 source crop (no inset)
  },
  // Craft / story
  { name: "craft-hands", file: "hands-crafting-painting-wooden-toys-work-2.jpg", width: 900, quality: 82 },
  // Gallery
  { name: "gallery-alphabet", file: "wooden-alphabet-puzzle-letters-toy-for-k-2.jpg", width: 900, quality: 82 },
  { name: "gallery-felt", file: "felt-quiet-book-busy-book-educational-fa-1.jpg", width: 900, quality: 82 },
  { name: "gallery-flatlay", file: "wooden-shape-sorter-toy-colorful-white-b-3.jpg", width: 900, quality: 82 },
  {
    // busy board 3: crop away the child inset in the bottom-right corner
    name: "gallery-busyboard",
    file: "handmade-wooden-busy-board-montessori-to-3.jpg",
    width: 900,
    quality: 82,
    crop: { top: 0, left: 0, width: 500, height: 380 },
  },
];

const meta = {};

for (const job of JOBS) {
  let pipeline = sharp(src(job.file)).rotate();
  if (job.crop) {
    pipeline = pipeline.extract({
      left: job.crop.left,
      top: job.crop.top,
      width: job.crop.width,
      height: job.crop.height,
    });
  }
  if (job.cropSquare) {
    pipeline = pipeline.resize({ width: job.width, height: job.width, fit: "cover" });
  } else {
    pipeline = pipeline.resize({ width: job.width, withoutEnlargement: true });
  }
  const info = await pipeline
    .webp({ quality: job.quality, effort: 5 })
    .toFile(join(out, `${job.name}.webp`));

  const blur = await sharp(join(out, `${job.name}.webp`))
    .resize(24, 24, { fit: "inside" })
    .blur(2)
    .webp({ quality: 45 })
    .toBuffer();

  meta[job.name] = {
    src: `/images/${job.name}.webp`,
    width: info.width,
    height: info.height,
    bytes: info.size,
    blur: `data:image/webp;base64,${blur.toString("base64")}`,
  };
  console.log(`✔ ${job.name}.webp  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
}

const header = `// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit by hand.
// Re-run: npm run images
export type SiteImage = {
  src: string;
  width: number;
  height: number;
  bytes: number;
  blur: string;
};

export const images = ${JSON.stringify(meta, null, 2)} as const satisfies Record<string, SiteImage>;
`;

writeFileSync(join(root, "src", "lib", "images.generated.ts"), header);
console.log("\n✔ src/lib/images.generated.ts written");

/* ——— Branded Open Graph image (1200×630) ——— */
const ogSvg = `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#FFFFFF"/>
  <g opacity="0.5">
    <circle cx="90" cy="90" r="7" fill="#ECE5F4"/><circle cx="180" cy="60" r="7" fill="#ECE5F4"/><circle cx="270" cy="110" r="7" fill="#ECE5F4"/>
    <circle cx="1000" cy="520" r="7" fill="#ECE5F4"/><circle cx="1100" cy="460" r="7" fill="#ECE5F4"/><circle cx="1140" cy="580" r="7" fill="#ECE5F4"/>
  </g>
  <!-- rainbow arcs -->
  <g transform="translate(1050,620)">
    <path d="M-130 0 A130 130 0 0 1 130 0" fill="none" stroke="#FF6B5C" stroke-width="26"/>
    <path d="M-104 0 A104 104 0 0 1 104 0" fill="none" stroke="#FFC94D" stroke-width="26"/>
    <path d="M-78 0 A78 78 0 0 1 78 0" fill="none" stroke="#2EC4B6" stroke-width="26"/>
    <path d="M-52 0 A52 52 0 0 1 52 0" fill="none" stroke="#8B7CF6" stroke-width="26"/>
  </g>
  <!-- sun logo -->
  <g transform="translate(140,180)">
    <g stroke="#2B2440" stroke-width="6">
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#FFC94D" transform="rotate(0)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#2EC4B6" transform="rotate(45)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#FF92B6" transform="rotate(90)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#8B7CF6" transform="rotate(135)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#FFC94D" transform="rotate(180)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#2EC4B6" transform="rotate(225)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#FF92B6" transform="rotate(270)"/>
      <rect x="-34" y="-84" width="68" height="22" rx="11" fill="#8B7CF6" transform="rotate(315)"/>
    </g>
    <circle cx="0" cy="0" r="72" fill="#FF6B5C" stroke="#2B2440" stroke-width="8"/>
    <circle cx="-26" cy="-12" r="9" fill="#2B2440"/>
    <circle cx="26" cy="-12" r="9" fill="#2B2440"/>
    <path d="M-24 22c9 12 39 12 48 0" fill="none" stroke="#2B2440" stroke-width="9" stroke-linecap="round"/>
  </g>
  <text x="280" y="195" font-family="Verdana, DejaVu Sans, sans-serif" font-size="72" font-weight="800" fill="#2B2440">HM Toys</text>
  <text x="280" y="262" font-family="Verdana, DejaVu Sans, sans-serif" font-size="34" font-weight="700" fill="#64597F">Handmade educational games for children</text>
  <g transform="translate(280,340)">
    <rect x="0" y="0" width="500" height="86" rx="43" fill="#FFC94D" stroke="#2B2440" stroke-width="6"/>
    <text x="250" y="55" text-anchor="middle" font-family="Verdana, DejaVu Sans, sans-serif" font-size="28" font-weight="800" fill="#2B2440">100% handmade with love</text>
  </g>
</svg>`;

await sharp(Buffer.from(ogSvg)).png().toFile(join(root, "public", "og.png"));
console.log("✔ public/og.png 1200x630");
